#!../../../bin/nsp -b

try {
	configfile = "../../config.ns";
	if (!lib.file.exists(configfile) && _ostype_.startswith("Windows")) {
		configfile = "../../config-win.ns";
	}
	include(configfile);
	include("../makelib.ns");
	CFLAGS = CFLAGS + " -I../../../include ";
	if (CC == 'cl.exe') CFLAGS = CFLAGS + "/c /Fo";
	else if (CC == 'tcc.exe') CFLAGS = CFLAGS + "-c -o";
	else CFLAGS = CFLAGS + "-c -o ";
	OBJECTS = "wingdi.o";
	TNAME = "libnsp_wingdi";
	if (cmd == null) if (_ARGS[2] == 'clean') cmd = 'clean'; else cmd = 'build';
	if (cmd == 'build') {
		t = newer2(OBJECTS, _LINKAGE_, TNAME);
		if (t > 0) {
			print("building ", _LINKAGE_, " lib wingdi\n");
			if (CC == 'cl.exe') lib.file.writeall("dlldefs.def", "LIBRARY\t\tlibnsp_wingdi\r\nEXPORTS\r\n\tnspwingdi_register_all\r\n\tnsplib_init\r\n");
			build_objs(CC, CFLAGS, OBJECTS, _LINKAGE_, TNAME);
			build_lib(CC, TNAME, OBJECTS, _LINKAGE_, TNAME);
		}
	} else if (cmd == 'clean') {
		build_clean(TNAME, OBJECTS);
	}
} catch (ex) {
	printf("build exception (wingdi): %s\n", ex.description);
}
